service: aws-node-express-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  stage: dev
  profile: deploy-aws

plugins:
  - serverless-offline

custom:
  prune:
    automatic: true
    number: 3

# Exclude files from deployment
package:
    exclude:
        - '.git/**'

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
